### ISSUE TITLE
Directory mismatch on pull

### ISSUE THREAD

**Issue by bootstrap314** [oras-project/oras-py#100]
When I pull an image, the directory specified by "outdir" is repeated. This causes the extracted files to be saved to the wrong directory:

For example, with the following code, this is my result:

```import oras.client
import os

from oras.logger import logger, setup_logger

client = oras.client.OrasClient()
print(client.version())

f = open("secret.json", "r")
password = f.read()

image = <image name:tag>

def pull_to_oci_layout(username, password, outdir, reference):
    try:
        hostname = reference.split("/")[0]
        result = client.login("_json_key", password, hostname=hostname)
        print(result)
        client.pull(
            allowed_media_type=[],
            overwrite=True,
            outdir="tmp",
            target=reference,
            debug=True,
        )
    except Exception as e:
        logger.exit(str(e))


pull_to_oci_layout(
    "_json_key",
    password,
    "tmp",
    image,
)
```

This yields the directory structure:
```
tmp
└── tmp
    ├── Cargo.lock
    ├── Cargo.toml
    ├── config.json
    ├── loader.wasm
    └── src
        ├── foundation.rs
        ├── foundation_callbacks.rs
        ├── gas.rs
        ├── getters.rs
        ├── internal.rs
        ├── lib.rs
        ├── owner.rs
        ├── owner_callbacks.rs
        ├── tests
        │   └── test_utils.rs
        └── types.rs
```

I've been trying to figure out why this is occurring but haven't figured it out yet. Has anyone else seen this?

**Comment by vsoch** [comment]
The logic you’d want to debug starts here: https://github.com/oras-project/oras-py/blob/db32c9828c8914eca40ba1cc86c7974b14b129c6/oras/provider.py#L774

**Comment by saketjajoo** [comment]
@vsoch, I am facing the same problem that the `outdir` is being repeated twice. Also, path aliases (e.g. `~` in mac = `$HOME` dir) do not get resolved. Example:
* outdir = `~/data` yields the complete path to be `$PWD/~/data/~/data/`
* outdir = `./data` yields the complete path to be `$PWD/data/data`

I believe I have a fix for this. Can I pick up this issue and propose a PR to fix it?

**Comment by vsoch** [comment]
Yes that would be excellent - please go ahead.

**Comment by saketjajoo** [comment]
PR to fix this: https://github.com/oras-project/oras-py/pull/106

**Comment by saketjajoo** [comment]
This issue can be marked as fixed/completed!

**Comment by vsoch** [comment]
Thank you @saketjajoo !
