### ISSUE TITLE
Features that we like in conda_oci_mirror

### ISSUE THREAD

**Issue by wolfv** [oras-project/oras-py#11]
Hi @vsoch,

awesome work on the initial implementation. I think I have some feedback based on our experience implementing something like this for `conda-oci-mirror`: https://github.com/mamba-org/conda_oci_mirror

We currently push three layers per "conda"-package to the OCI registry. The first layer is the `.tar.bz2` package file. The second layer is the `index.json` file, containing the metadata and dependencies of the package (useful for creating an index over the whole repo). The third file is a `.tar.gz` of the `info/...` directory that every conda package contains (that directory contains a list of all files of the package and more interesting metadata that would be nice to access without downloading the whole package).

In our client, we added some easy-access functions for the latter two objects. For the `index.json` we first fetch the manifest and look for the layer with the appropriate mediaType (`vnd.conda.index+json` or something like that) and then pull only that layer blob and immediately parse it to json using `res.json()` from `requests`.

For the `.tar.gz` file we pass it on to the `tarfile` reader to have access to all files inside in a nice way.

Maybe exposing the `get_blob` without an underscore could be cool?

I thought having a `Layer` class (with a `.to_json()` function) might be nicer than the `NewLayer` free function that returns a dict (this is just a nitpick, I guess)

We also have [a function to retrieve all tags](https://github.com/mamba-org/conda_oci_mirror/blob/f300085bdf7725b2d134f2c48db415d7129691fa/conda_oci_mirror/oci.py#L49-L75
) for a given container. This is necessary for efficient mirroring and could also fit well into `oras-py` I think.
 
Anyways, this looks super promising, thanks for your work!!

**Comment by wolfv** [comment]
Btw. just in case you wanted to see one of our 'packages' as described here on the OCI registry: https://github.com/orgs/channel-mirrors/packages/container/package/conda-forge%2Fosx-64%2Fxtensor

**Comment by vsoch** [comment]
hey @wolfv ! It looks like the request to get a manifest returns a 500 error? I tried interacting with:

Regular oras:

```
$ oras pull -a ghcr.io/channel-mirrors/conda-forge/osx-64/xtensor:0.9.0-0
Error: unexpected status code [manifests 0.9.0-0]: 500 Internal Server Error
```

docker manifest inspect

```
$ docker manifest inspect ghcr.io/channel-mirrors/conda-forge/osx-64/xtensor:0.9.0-0
received unexpected HTTP status: 500 Internal Server Error
```
crane https://crane.ggcr.dev/ls/ghcr.io/channel-mirrors/conda-forge/osx-64/xtensor

And of course oras-py (where I first saw the error). I did a sanity check with a simple package I have, and it correctly sends back 401 asking for auth:

https://ghcr.io/v2/singularityhub/github-ci/manifests/latest

And with auth I can get the manifest:

{'schemaVersion': 2,
 'config': {'mediaType': 'application/vnd.sylabs.sif.config.v1',
  'digest': 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  'size': 0},
 'layers': [{'mediaType': 'application/vnd.sylabs.sif.layer.v1.sif',
   'digest': 'sha256:acb1ec674e686f4ba7a0e5c0ce1d41b6c2a5f5f1b9b9baca9c612f794faa3f8e',
   'size': 798720,
   'annotations': {'org.opencontainers.image.title': 'container.sif'}}]}

Here is the comparison that doesn't work:

https://ghcr.io/v2/channel-mirrors/conda-forge/osx-64/xtensor/manifests/0.9.0-0

So I think there are a few things we can try. If it's an issue with the tag, perhaps we can try a simple tag like "latest" that removes special characters? And do you have any interaction with this artifact that has worked? it could also be an ephemeral bug.

**Comment by vsoch** [comment]
Yes perfecto! :tada: 

```
In [1]: response
Out[1]: <Response [200]>

In [2]: response.json()
Out[2]: 
{'schemaVersion': 2,
 'config': {'mediaType': 'application/vnd.unknown.config.v1+json',
  'digest': 'sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a',
  'size': 2},
 'layers': [{'mediaType': 'application/vnd.conda.package.v1',
   'digest': 'sha256:920513145f842c15e2b694b858b2e98281691dda5bd8b37344d4c507308cf141',
   'size': 57739,
   'annotations': {'org.opencontainers.image.title': 'xtensor-0.9.0-0.tar.bz2'}},
  {'mediaType': 'application/vnd.conda.info.v1.tar+gzip',
   'digest': 'sha256:19fd4053701485a0777a684b77389667c753a98c3988206e1e2e51b6ede041b9',
   'size': 5852,
   'annotations': {'org.opencontainers.image.title': 'xtensor-0.9.0-0/info.tar.gz'}},
  {'mediaType': 'application/vnd.conda.info.index.v1+json',
   'digest': 'sha256:032a19b7aa2b13e1146a6bace7307c76b3769389439759845ef322207f7d0417',
   'size': 222,
   'annotations': {'org.opencontainers.image.title': 'xtensor-0.9.0-0/info/index.json'}}]}
```
It must be a bug with channel-mirrors, no worries about that, this new URI is perfect for me to work on the example. Thank you!

**Comment by vsoch** [comment]
okay here is an example / demo! https://github.com/oras-project/oras-py/blob/6600cc59d80e83c3900ebb375350bbd62a552510/examples/conda-mirror.py 

I suspect for your actual use case you'll want to have those each be a separate function, and then an actual download of the archive to somewhere (which I didn't do!) This should be okay for a first pass, but when this first chunk of work is in let's see if we can turn it into more of a useful client vs just printing pieces to the screen. If you have a workflow example we can insert into that might be helpful!

**Comment by vsoch** [comment]
@wolfv do you have any further request for example or to update a feature? Otherwise I think we can close. Thank you!

**Comment by vsoch** [comment]
Closing, thanks again!
