### ISSUE TITLE
Schema Validation Error on Pull from artefact push with Oras 1.1.0

### ISSUE THREAD

**Issue by mariusbertram** [oras-project/oras-py#126]
I get an error on Pulling this artifact ghcr.io/mariusbertram/oci_test:latest

The Image was pushed with Oras 1.1.0 installed via brew 
`oras push ghcr.io/mariusbertram/oci_test:latest IdeaProjects/oci/test/:application/vnd.acme.rocket.docs.layer.v1+tar`

This is the Error Output:

`File "/opt/homebrew/lib/python3.12/site-packages/oras/provider.py", line 866, in get_manifest
        jsonschema.validate(manifest, schema=oras.schemas.manifest)
      File "/opt/homebrew/lib/python3.12/site-packages/jsonschema/validators.py", line 1312, in validate
        raise error
    jsonschema.exceptions.ValidationError: Additional properties are not allowed ('artifactType' was unexpected)
  
    Failed validating 'additionalProperties' in schema:
        {'$schema': 'http://json-schema.org/draft-07/schema',
         'additionalProperties': False,
         'properties': {'annotations': {'type': ['object', 'null', 'array']},
                        'config': {'properties': {'annotations': {'type': ['object',
                                                                           'null',
                                                                           'array']},
                                                  'digest': {'type': 'string'},
                                                  'mediaType': {'type': 'string'},
                                                  'size': {'type': 'number'}},
                                   'type': 'object'},
                        'layers': {'items': {'properties': {'annotations': {'type': ['object',
                                                                                     'null',
                                                                                     'array']},
                                                            'digest': {'type': 'string'},
                                                            'mediaType': {'type': 'string'},
                                                            'size': {'type': 'number'}},
                                             'type': 'object'},
                                   'type': 'array'},
                        'mediaType': {'type': 'string'},
                        'schemaVersion': {'type': 'number'},
                        'subject': {'type': ['null', 'object']}},
         'required': ['schemaVersion', 'config', 'layers'],
         'title': 'Manifest Schema',
         'type': 'object'}
  
    On instance:
        {'annotations': {'org.opencontainers.image.created': '2024-03-18T08:15:46Z'},
         'artifactType': 'application/vnd.unknown.artifact.v1',
         'config': {'data': 'e30=',
                    'digest': 'sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a',
                    'mediaType': 'application/vnd.oci.empty.v1+json',
                    'size': 2},
         'layers': [{'annotations': {'io.deis.oras.content.digest': 'sha256:097fb7596f38dd92c6be6a3ea188233ba1021c99af143dcd3b3059b1c6c965c5',
                                     'io.deis.oras.content.unpack': 'true',
                                     'org.opencontainers.image.title': 'IdeaProjects/oci/test'},
                     'digest': 'sha256:3f0f2965ee017a5b26e83e9e64b6f218e75f9c4047b62f663db61623c2502065',
                     'mediaType': 'application/vnd.oci.image.layer.v1.tar+gzip',
                     'size': 193}],
         'mediaType': 'application/vnd.oci.image.manifest.v1+json',
         'schemaVersion': 2}
`

**Comment by vsoch** [comment]
It looks to just be a missing field. Does it work if you comment out the validation line here https://github.com/oras-project/oras-py/blob/6c9fd25cddbdcea0bb5929a07dfb5378edeb786c/oras/provider.py#L866 ?

**Comment by mariusbertram** [comment]
Yes it does work. It also works if I set "additionalProperties" to True in the schema.py

**Comment by vsoch** [comment]
Closed with #127
