### ISSUE TITLE
logger.exit(...)

### ISSUE THREAD

**Issue by xarses** [oras-project/oras-py#154]
I recently upgraded from 0.1.17 to 0.2.2, and found that there are two cases  in the internals ([here](https://github.com/oras-project/oras-py/blob/main/oras/auth/__init__.py#L14) and [here](https://github.com/oras-project/oras-py/blob/main/oras/provider.py#L978)) where `logger.exit(...)`[is used](https://github.com/oras-project/oras-py/blob/main/oras/logger.py#L214) which causes a `sys.exit(1)` rather than raising an exception. Is there a reasoning for handling the error(s) this way instead of letting the caller handle these?

**Comment by vsoch** [comment]
We should raise a ValueError instead (with the same message). Would you care to open a PR to make this change?
