### ISSUE TITLE
Authentication against gitlab registry fails

### ISSUE THREAD

**Issue by magelisk** [oras-project/oras-py#49]
Authentication against the Container registry in gitlab appears to fail. The cause is because the authentication expects the `service` parameter is expected to be a POST parameter, and not a header. 

A fix here is very easy in `authenticate_request` (https://github.com/oras-project/oras-py/blob/main/oras/provider.py#L691) 

```
        params = {}  # define further up

        h = oras.auth.parse_auth_header(authHeaderRaw)
        if h.service:
            params["service"] = h.service  # added
            headers.update(
                {
                    "Service": h.service,
                    "Accept": "application/json",
                    "User-Agent": "oras-py",
                }
            )
```

I know this works, I've patched in in my local branch and it works for both private gitlab container registries. However, I don't know if this may introduce compatibility issues with other container registries. I assume they would ignore unused params, but I don't know this for sure

# Output Details
When I run this below script I get the following console:
```
> registry = Registry(hostname="registry.gitlab.company.com:443")
> client = oras.client.OrasClient(registry=registry)
> res = client.pull(target="registry.gitlab.us.lmco.com:443/magelisk/artifact-testing/transfer-manifest.yaml:0.0.1", outdir="./TEMP")

authentication required
Issue with https://registry.gitlab.company.com:443/v2/magelisk/artifact-testing/transfer-manifest.yaml/manifests/0.0.1:
Unauthorized
```

The `originalResponse.headers` that goes into the `authenticate_request` function is:

```
{'Content-Type': 'application/json', 'Date': 'Wed, 26 Oct 2022 03:08:21 GMT', 'Docker-Distribution-Api-Version': 'registry/2.0', 'Server': 'nginx', 'Www-Authenticate': 'Bearer realm="https://gitlab.company.com/jwt/auth",service="container_registry",scope="repository:magelisk/artifact-testing/transfer-manifest.yaml:pull"', 'X-Content-Type-Options': 'nosniff', 'Content-Length': '197', 'Connection': 'keep-alive'}
```
The service of `container_registry` is definitely correct, but not in thne headers.

The way I actually figure out what was wrong was by comparing the ORAS CLI debug output. It gets the same 401, and you can see resulting request URL in last line with the param set

```
$ oras pull registry.gitlab.us.lmco.com:443/magelisk/artifact-testing/transfer-manifest.yaml:0.0.1 --debug

DEBU[0000]  Request URL: "https://registry.gitlab.company.com:443/v2/magelisk/artifact-testing/transfer-manifest.yaml/manifests/0.0.1"
DEBU[0000]  Request method: "GET"
DEBU[0000]  Request headers:
DEBU[0000]    "Accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.cncf.oras.artifact.manifest.v1+json"
DEBU[0000]    "User-Agent": "oras/0.15.0"
DEBU[0000]  Response Status: "401 Unauthorized"
DEBU[0000]  Response headers:
DEBU[0000]    "Content-Type": "application/json"
DEBU[0000]    "Connection": "keep-alive"
DEBU[0000]    "Www-Authenticate": "Bearer realm=\"https://gitlab.company.com/jwt/auth\",service=\"container_registry\",scope=\"repository:magelisk/artifact-testing/transfer-manifest.yaml:pull\""
DEBU[0000]    "X-Content-Type-Options": "nosniff"
DEBU[0000]    "Server": "nginx"
DEBU[0000]    "Content-Length": "184"
DEBU[0000]    "Docker-Distribution-Api-Version": "registry/2.0"
DEBU[0000]    "Date": "Wed, 26 Oct 2022 03:12:22 GMT"
DEBU[0000]  Request URL: "https://gitlab.company.com/jwt/auth?scope=repository%3Amagelisk%2Fartifact-testing%2Ftransfer-manifest.yaml%3Apull&service=container_registry"
```

**Comment by vsoch** [comment]
@magelisk does the registry originally provide a 401 response, and if so, is there a Www-autheticate header (and could you show me?) that usually dictates what the authentication request needs.

**Comment by magelisk** [comment]
I've updated the original description with a lot more output which I think will show everything you're looking for

**Comment by vsoch** [comment]
Thank you, that’s perfect! The bug here is not properly parsing that - we should see the service paean in that header and add it. I might not get to this tonight but can definitely make some time to fix it up tomorrow, likely in the evening. Thank you for reporting this!

**Comment by magelisk** [comment]
Awesome. I made an MR with what I had done locally as a starting point, but if it's too much of a 'hack' of course feel free to close it. Thanks!

**Comment by vsoch** [comment]
This is fixed in https://github.com/oras-project/oras-py/releases/tag/0.0.17. Thanks again @magelisk!
