### ISSUE TITLE
[Feature] Skip tls verifikation

### ISSUE THREAD

**Issue by mariusbertram** [oras-project/oras-py#95]
Hello,
it would be nice feature to be able to skip tls verification for the Oras.Client.
Like on the oras cli.

**Comment by vsoch** [comment]
Did you try the insecure parameter? https://github.com/oras-project/oras-py/blob/8c1f7cc64a97e0580024b642c6eefeb07968799b/oras/client.py#L32

**Comment by mariusbertram** [comment]
Yes I tried the parameter. But I get this Error on MacOS with Python 3.11.4 and in an alpine:python3.11 image.
`raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.178.43', port=443)`

**Comment by mariusbertram** [comment]
I think it's a bug. The insecure parameter is not pass through to oras.provide and do_request() 
https://github.com/oras-project/oras-py/blob/8c1f7cc64a97e0580024b642c6eefeb07968799b/oras/provider.py#L810

**Comment by mariusbertram** [comment]
I made a pull request with an fix #96

**Comment by vsoch** [comment]
Thank you @mariusbertram ! It should be released to pypi shortly, version 0.1.2.

**Comment by mariusbertram** [comment]
The Version 0.1.2 is on pypi but version 0.1.2 is smaller than 0.1.19. I think this version schould be 0.1.20

**Comment by vsoch** [comment]
Good call - let me fix that up.
